### ISSUE TITLE
Compilation fails on OS X

### ISSUE THREAD

**Issue by sekrit-twc** [HomeOfVapourSynthEvolution/VapourSynth-TDeintMod#6]
The following issues prevent compilation with the default toolchain on OS X:

1. TDeintMod.cpp needs to include <cstdlib> for std::abs(int) and <cmath> for std::log2.
2. -Bsymbolic is not a valid linker flag on OS X. It's not clear why this flag is set, as the plugin links to no external libraries.
3. Build system should only check vapoursynth_CFLAGS and not vapoursynth_LIBS. There is no reason to link to libvapoursynth

**Comment by HolyWu** [comment]
For the build system, I really don't know what most of the flags do since I am not a Linux/OS X user. It's simply copied and modified from the script used by d2vsource at first. Do you think switching to the build system used by duhhater is better? Although I may still need to figure out what lines to change then.

**Comment by sekrit-twc** [comment]
There's no need to change the build system. You should simply remove -Bsymbolic from the default LDFLAGS because you are not linking with ffmpeg like d2vsource, as well as removing vapoursynth from the list of libraries required.

**Comment by HolyWu** [comment]
Does the latest commit do the trick?

**Comment by sekrit-twc** [comment]
Yes. Issue is fixed.
